# Project information
site_name: TinySpark
site_description: Tiny board, big predictions.
site_author: J Siderius
copyright: Copyright &copy; 2023 J Siderius

repo_name: j-siderius/TinySpark
repo_url: https://github.com/j-siderius/TinySpark

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - announce.dismiss
    - attr_list
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    # - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: blue
      accent: teal
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
  font:
    text: Open Sans
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/logo.png

plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - with-pdf:
      cover_title: TinySpark
      cover_subtitle: Tiny board, big predictions
      output_path: assets/pdf/main.pdf 
      # cover_logo: assets/images/
      # render-js: true
      # headless_chrome_path: headless-chromium

extra_css:
#    - css/extra.css

markdown_extensions:
#    - toc:
#        permalink:
  - attr_list
#    - def_list
#    - tables
#    - callouts
#    - mdx_gh_links:
#        user: mkdocs
#        repo: mkdocs
#    - mkdocs-click
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format 
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
nav:
  - Home: index.md
  - TinySpark:
    - Introduction: kit/introduction.md
    - Platform: kit/platform.md
    - TinyML development kit: kit/devkit.md
    - Programming: kit/programming.md
  - Chapter 1:
    - Introduction: chapter1/introduction.md
    - Neuron: chapter1/neuron.md
    - Logic gates: chapter1/logic_gates.md
    - Logic gates on micro: chapter1/logic_gates_micro.md
  - Chapter 2:
    - Introduction: chapter2/introduction.md
    - Network connections: chapter2/network_connections.md
    - Plant monitoring: chapter2/plant_monitoring.md
    - Plant monitoring on micro: chapter2/plant_monitoring_micro.md
  - About: 
    - Project: about/project.md
    - License: about/license.md
