# Project information
site_name: TinySpark
site_description: Tiny board, big predictions.
site_author: J Siderius
copyright: Copyright &copy; 2023 J Siderius
# repo_url: https://jsiderius.github.io/TinySpark

theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    # - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
#    - redirects:
#        redirect_maps:
#            user-guide/plugins.md: dev-guide/plugins.md
#            user-guide/custom-themes.md: dev-guide/themes.md
#            user-guide/styling-your-docs.md: user-guide/choosing-your-theme.md
  - with-pdf:
      cover_title: TinySpark
      cover_subtitle: Tiny board, big predictions
      output_path: pdf/main.pdf 
      # cover_logo: assets/images/
      # toc_title: Contents

nav:
  - Home: index.md
#    - Getting Started: getting-started.md
#    - User Guide: user-guide/
#    - Developer Guide: dev-guide/
#    - About:
#        - Release Notes: about/release-notes.md
#        - Contributing: about/contributing.md
#        - License: about/license.md


# TODO: Fix indentation below in next commit

extra_css:
#    - css/extra.css

markdown_extensions:
#    - toc:
#        permalink:
#    - attr_list
#    - def_list
#    - tables
#    - callouts
#    - mdx_gh_links:
#        user: mkdocs
#        repo: mkdocs
#    - mkdocs-click
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
